# This is the development dockerfile with React's debugging server enabled.

# Specify the base image to use from Docker Hub repository -> repository:tag
# Note: There are some dependency issues with node 17, so node 16 will used for now.
FROM node:16-alpine

# Specify the working directory -> all commands after this command will be executed relative to this path in the container
WORKDIR '/frontend'

# Let Docker know what port is to be used
EXPOSE 3000

# Copy files from the source directory (current folder) into the specfied folder and working directory
# First move the package.json since it should rarely be changed
COPY package.json .
# Install dependencies based on package.json
RUN npm install
# Copy all other files into the container
COPY . .

# Run the following command when container is finished building
CMD ["npm", "start"]